### PR TITLE
Unlock OS thread after netns is restored

### PR DESCRIPTION
**Pull request by booxter**
The current ns package code is very careful about not leaving the calling
thread with the overridden namespace set, for example when origns.Set() fails.
This is achieved by starting a new green thread, locking its OS thread, and
never unlocking it. Which makes golang runtime to scrap the OS thread backing
the green thread after the go routine exits.

While this works, it's probably not as optimal: stopping and starting a new OS
thread is expensive and may be avoided if we unlock the thread after resetting
network namespace to the original. On the other hand, if resetting fails, it's
better to leave the thread locked and die.

While it won't work in all cases, we can still make an attempt to reuse the OS
thread when resetting the namespace succeeds. This can be achieved by unlocking
the thread conditionally to the namespace reset success.

Signed-off-by: Ihar Hrachyshka <ihrachys@redhat.com>

### CODE REVIEW

**Comment by booxter** [comment]
@rmohr @davidvossel

**Comment by jellonek** [comment]
We don't have this noted anywhere specifically (and probably this should be changed) that we are trying to be compliant only with last 3 stable versions of golang, so right now with go >=1.11.

Our tests are running only against https://github.com/containernetworking/plugins/blob/master/.travis.yml#L5 these versions.

**Comment by rmohr** [comment]
> We don't have this noted anywhere specifically (and probably this should be changed) that we are trying to be compliant only with last 3 stable versions of golang, so right now with go >=1.11.

Then the PR should be good. Thanks.

**Comment by mars1024** [comment]
@jellonek @rmohr A small question, why should we force-unlock the OS thread? I think the lock will be released after the goroutine exits.

**Comment by rmohr** [comment]
> @jellonek @rmohr A small question, why should we force-unlock the OS thread? I think the lock will be released after the goroutine exits.

Instead of unlocking the thread, the thread gets reaped when the routine exits when it is not unlocked: https://golang.org/src/runtime/proc.go?s=102346:102367#L3574.

We will get new threads if needed, but it makes the operation definitely heavier.

**Comment by jellonek** [comment]
@mars1024 To understand that you need to know about long standing bug in golang which was leading to reusing threads with changed netns by other goroutines, while they were expecting that they are running in the original one netns.
PTAL on https://www.weave.works/blog/linux-namespaces-golang-followup

**Comment by jellonek** [comment]
Let's wait for next maintainers meeting (02.26) with merge.

**Comment by bboreham** [comment]
Historical note: here is the statement that "`UnlockOSThread` is not safe for use in any library code"
https://github.com/golang/go/issues/20458.
This was fixed in Go 1.10 as noted.

**Pull request merged**
