### PR TITLE
ipvlan: make master config as optional

### PR DESCRIPTION
**Pull request by s1061123**
This change makes ipvlan master parameter optional.
Default to default route interface as macvlan does.

### CODE REVIEW

**Comment by dougbtv** [comment]
Just a note that this would make it consistent with the macvlan plugin, for a reference see Tomo's change to macvlan @ #298

**Comment by s1061123** [comment]
CI failure will be fixed by https://github.com/containernetworking/plugins/pull/529 I believe.

**Comment by dougbtv** [comment]
Any chance we could get a CI re-run on this one #529 has merged. Thanks!

**Comment by jellonek** [comment]
@dougbtv this would require rebase to be done by @s1061123

**Comment by jellonek** [comment]
Anyway - LGTM.

**Review by jellonek — APPROVED** [review]

**Comment by squeed** [comment]
lgtm!

**Pull request merged**
