### PR TITLE
bridge: various fixes

### PR DESCRIPTION
**Pull request by squeed**
* Don't set the MAC, send gratuitous arp instead
* Set the bridge's MAC to itself
* Only disable DAD when necessary

Fixes: #60 #59 #52

### CODE REVIEW

**Comment by rosenhouse** [comment]
Is there any way we can add test coverage for these changes?  

I've been thinking about refactoring this plugin, but its scarier to attempt when there are important features that might break while the tests remain green.

**Comment by squeed** [comment]
Yeah, good point. Most of this should be testable.

**Comment by squeed** [comment]
@rosenhouse added a test for the "stable mac" case. Not sure how to reasonably test the other changes.

**Comment by rosenhouse** [comment]
@squeed looks like it went red

**Comment by squeed** [comment]
Once #56 is merged we should see fewer test failures.

A lot of these tests are dancing around with namespaces, making them non-deterministic.

**Comment by rosenhouse** [comment]
Yeah, I don't see how to add functional tests either.  (all the more reason to refactor to a more dependency-injected style where we can have unit tests of the application-object).

LGTM

**Comment by wanghaibo** [comment]
can we set the MAC（GenerateByIp） in container and send gratuitous arp at the same time? in some case,we need container mac address stable when ip not change

**Pull request merged**
