### PR TITLE
Configure a specific mac address on the pod interface.

### PR DESCRIPTION
**Pull request by SchSeba**

### CODE REVIEW

**Comment by dcbw** [comment]
@SchSeba this use-case is exactly what MAC support was added to the tuning plugin for, so I'd suggest that you chain the tuning plugin instead of adding the duplicate functionality to the bridge plugin.

**Comment by s1061123** [comment]
Here is the examples (verified with `k8s: v1.11.4`):

```
[centos@kube-master ~]$ cat test.yml 
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-conf
spec:
  config: '{
        "name": "mynet",
        "plugins" : [
          {
            "type": "bridge",
            "bridge": "mynet0",
            "isDefaultGateway": true,
            "forceAddress": false,
            "ipMasq": true,
            "hairpinMode": true,
            "ipam": {
                "type": "host-local",
                "subnet": "10.10.0.0/16"
            }
          },
          {
              "type": "tuning",
              "mac": "c2:b0:57:49:47:f1"
          }
        ]
     }'
---
apiVersion: v1
kind: Pod
metadata:
  name: centos-mac-pod
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { 
              "name": "bridge-conf"
            }
         ]'
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: docker.io/centos/tools:latest
    command: 
    - /sbin/init
[centos@kube-master ~]$ kubectl create -f test.yml 
networkattachmentdefinition.k8s.cni.cncf.io/bridge-conf created
pod/centos-mac-pod created
[centos@kube-master ~]$ kubectl exec centos-mac-pod -- ip address
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
3: eth0@if7: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default 
    link/ether 0a:58:0a:f4:01:02 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.244.1.2/24 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::ec89:a5ff:fe27:e6d9/64 scope link tentative dadfailed 
       valid_lft forever preferred_lft forever
5: net1@if9: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether c2:b0:57:49:47:f1 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.10.0.2/16 scope global net1
       valid_lft forever preferred_lft forever
    inet6 fe80::c0b0:57ff:fe49:47f1/64 scope link 
       valid_lft forever preferred_lft forever
```

**Comment by SchSeba** [comment]
@s1061123 Thanks for the answer. 
Maybe I don't understand this correctly but now all the pods using the same network attachment CRD will get the same mac?

There is a way to configure the mac on the pod annotation?

**Comment by s1061123** [comment]
https://github.com/intel/multus-cni/pull/148

Add static without mac config in json, like above example, then "mac" annotation can do that.

**Comment by SchSeba** [comment]
@s1061123 Nice thanks! I will try it and report

**Comment by SchSeba** [comment]
@s1061123 Update I can't make it work.

I am using 
multus - (nfvpe/multus:snapshot@sha256:5b8c07877ed35a7555917971901aa1c6fbc48056e686cf6948687fda878e4919)

cni/plugins https://github.com/containernetworking/plugins/releases/download/v0.7.4/cni-plugins-amd64-v0.7.4.tgz

CRD -
```yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-mac
spec:
  config: '{
        "cniVersion": "0.3.1",
        "name": "mynet",
        "plugins" : [
          {
            "type": "bridge",
            "bridge": "mynet0",
            "ipam": {
                "type": "host-local",
                "subnet": "10.10.0.0/16"
            }
          },
          {
              "type": "tuning"
          }
        ]
     }'
```

pod yaml
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: centos-mac-pod
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { 
              "name": "bridge-mac",
              "mac": "c2:b1:57:49:47:f1"
            }
         ]'
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: centos
    command: ['sh', '-c', 'yum install -y iproute net-tools; sleep infinity']
```

logs from multus
```
2018-12-03T04:46:31-05:00 [debug] validateIfName: /proc/22705/ns/net, net1
2018-12-03T04:46:31-05:00 [debug] Set MAC address "c2:b1:57:49:47:f1" to "net1"
2018-12-03T04:46:31-05:00 [debug] conflistAdd: &{3f2fcea34d533424660807d9691adfbd118dd6163eeb799ed547f9c15044435a /proc/22705/ns/net net1 [[IgnoreUnknown 1] [K8S_POD_NAMESPACE default] [K8S_POD_NAME centos-mac-pod] [K8S_POD_INFRA_CONTAINER_ID 3f2fcea34d533424660807d9691adfbd118dd6163eeb799ed547f9c15044435a]] map[] }, { "cniVersion": "0.3.0", "name": "mynet", "plugins" : [ { "type": "bridge", "bridge": "mynet0", "ipam": { "type": "host-local", "subnet": "10.10.0.0/16" } }, { "type": "tuning" } ] }, /opt/cni/bin
2018-12-03T04:46:31-05:00 [debug] LoadNetworkStatus: Interfaces:[{Name:mynet0 Mac:52:54:00:ff:8b:7a Sandbox:} {Name:veth4b7ea489 Mac:82:07:33:ef:3b:d2 Sandbox:} {Name:net1 Mac:62:82:30:76:c7:f9 Sandbox:/proc/22705/ns/net}], IP:[{Version:4 Interface:0xc420404ec8 Address:{IP:10.10.0.28 Mask:ffff0000} Gateway:10.10.0.1}], DNS:{Nameservers:[] Domain: Search:[] Options:[]}, mynet, false
2018-12-03T04:46:31-05:00 [debug] SetNetworkStatus: &{0xc420311ce0 default centos-mac-pod}, [0xc4203520b0 0xc420352bb0]
```

**Comment by SchSeba** [comment]
Hi @s1061123 I was able to make this work by building the tuning plugins from master.
Can you please trigger a new release?

**Comment by dcbw** [comment]
Looks like the chaining is working as intended with recent code.  Closing this as the issue is fixed.

**Comment by SchSeba** [comment]
@dcbw can you please make a release so there is no need to build manually the plugins?

**Pull request closed without merging**
