### PR TITLE
delete link and ip if err when cmdAdd to avoid resource leak.

### PR DESCRIPTION
**Pull request by oilbeater**
We encounter link and ip leak in production, one reason on cni side is that it not recycle resource when err happens. 

We first meet the issue in macvlan plugin, however this issue appears in other plugins as well, if this modification is reasonable I will apply the change to other plugins.

### CODE REVIEW

**Comment by rosenhouse** [comment]
I've seen others add this sort of code to plugins as well.

The CNI spec says "[plugin DEL should be idempotent](https://github.com/containernetworking/cni/blob/master/SPEC.md#general-considerations)".  The intention was that **runtimes** could run `DEL` after any failed ADD.  That way plugins would not need to contain this sort of self-cleanup logic.  It seems like your runtime (kubernetes? mesos? something else?) doesn't do this.

I'm wondering if the right solution is maybe one of the following:
1. fix your runtime and *also* add a line to the spec recommending that runtimes do this
2. make this sorts of change to all our reference plugins and *also* add a line to the spec to explicitly recommend this behavior from other plugins

maybe other @containernetworking/cni-maintainers have thoughts too...

**Comment by oilbeater** [comment]
We encounter this problem in Kubernetes. As our investigation many parts will lead resource leak (kubelet failed to call cni delete, docker leak netns, network partition and other inconsistence between other components ...) We have an above-all gc script that monitors all stats and deal with the inconsistence.

From my point, every components should do their best to provide atomic operations and keep a consistent state, as other parts the components rely on for gc may fail. If a create operation failed in the middle, it should not make the system to an unknown state, which also lead create not an idempotent operation. 

I'd like to change other reference plugins to recycle resources if failed in middle if this is solution is preferred.

**Comment by oilbeater** [comment]
any update on this? @rosenhouse

**Comment by bboreham** [comment]
On principle, choice 2 seems better.  Although it is more code for us to add.

**Comment by squeed** [comment]
We briefly discussed this in the maintainer's meeting. My position:
- Plugins that "wrap" other plugins (most notably: ipam) should try to call DEL on failure during ADD
- Runtimes should call DEL if ADD fails.

This is a change to libcni and the spec.

**Comment by squeed** [comment]
Also, we can probably get this in to spec version v0.4.0

**Comment by rosenhouse** [comment]
This gets complicated when you have a chain of plugins.  Is it the responsibility of the library to call DEL immediately on ADD failure?  I'm a bit worried about hiding errors from the runtime.  Runtimes should have the opportunity to inspect and log each error.

@bboreham had some more thoughts on this in the call today.

**Pull request merged**
