### PR TITLE
Add support for in-container master for vlans

### PR DESCRIPTION
**Pull request by mmirecki**
Add support for in-container master for the vlan plugin

docs: https://github.com/containernetworking/cni.dev/pull/109

### CODE REVIEW

**Comment by mmirecki** [comment]
@dougbtv @dcbw @s1061123 Could you please take a look?

**Comment by dougbtv** [comment]
This seems fairly straightforward to me, at least the code changes. But, I'm also interested in what we'll provide for docs / explain the usage as well.

**Comment by mmirecki** [comment]
> This seems fairly straightforward to me, at least the code changes. But, I'm also interested in what we'll provide for docs / explain the usage as well.

We have this doc PR for this: https://github.com/containernetworking/cni.dev/pull/109

**Review by dougbtv — APPROVED** [review]

**Review by s1061123 — COMMENTED** [review]
Almost good. Thank you  for the PR.

BTW, is there any reason why you don't add tests for 'linkInContainer' option in vlan_test.go?

**Comment by mmirecki** [comment]
> Almost good. Thank you for the PR.
> 
> BTW, is there any reason why you don't add tests for 'linkInContainer' option in vlan_test.go?

Tests modified. Thanks for catching this.

**Comment by mmirecki** [comment]
@dcbw can you please take a look?

**Pull request merged**
