### PR TITLE
Support "args" in static and tuning

### PR DESCRIPTION
**Pull request by s1061123**
Support "args" field in JSON config to additional configuration in static and tuning plugin.

### CODE REVIEW

**Comment by dcbw** [comment]
@s1061123 could you rebase and update? Thanks!

**Comment by Elegant996** [comment]
How would one configure the gateway if `ips` were set? Thanks!

**Comment by s1061123** [comment]
@Elegant996 I expect that gateway should be configured at conf file of static, not args. So conf file still has gateway field as following.

```
(snip)
		"addresses": [
			{
				"gateway": "10.10.0.254"
			},
(snip)
```

**Comment by s1061123** [comment]
@dcbw rebase and update done!

**Comment by Elegant996** [comment]
@s1061123 I thought the same but since `address` is a required field for `addresses` we get an invalid CIDR error:

```
error in getting result from AddNetworkList: invalid CIDR : invalid CIDR address: , failed to clean up sandbox container
```

Unfortunately `"routes": [ { "dst": "0.0.0.0/0", "gw": "10.10.5.1" } ]` only affects the `main` routing table.

Thanks!

**Comment by s1061123** [comment]
Args overwrites conf so you can put dummy val in conf.

**Comment by Elegant996** [comment]
Might be something to specific to `static`  then

```
(snip)
          "addresses": [
            {
                "address": "10.10.5.29/24",
                "gateway": "10.10.5.1"
            }
          ]
(snip)
```

However, now the error just contains the invalid CIDR:

```
error in getting result from AddNetworkList: invalid CIDR 10.10.5.29: invalid CIDR address: 10.10.5.29, failed to clean up sandbox container
```

This error only appears if the `ips` annotation is used for the pod:

```
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
          {
            "name": "macvlan-conf",
            "ips": "10.10.5.30/24"
          }
        ]'
```

Strangely enough, the pod will have an additional interface with `10.10.5.29/24` while producing the above error instead of the one specified in the annotations.

Thanks!

**Comment by s1061123** [comment]
@Elegant996 Could you please let me know which implementation is used for the testing(including cni runtime). Could you provide cni config and how to test it?

**Comment by Elegant996** [comment]
Using `multus` as the CNI runtime, the below would be the `cni` config:

```
---
kind: NetworkAttachmentDefinition
apiVersion: "k8s.cni.cncf.io/v1"
metadata:
  name: macvlan-conf
spec: 
  config: '{
    "cniVersion": "0.3.1",
    "name": "macvlan-conf",
    "plugins": [
      {
        "type": "macvlan",
        "master": "net0",
        "ipam": {
          "type": "static",
          "addresses": [
            {
                "gateway": "10.10.5.1"
            }
          ],
          "dns": {
            "nameservers" : ["10.10.5.1"]
          }
        }
      },
      {
        "type": "tuning"
      },
      {
        "type": "sbr"
      }
    ]
  }'
```

Now we would define `ips` using annotations in the pod:
```
(snip)
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
          {
            "name": "macvlan-conf",
            "ips": "10.10.5.30/24"
          }
        ]'
(snip)
```

Unfortunately, this returns the following error with no CIDR since it wasn't defined in the config under the `address` field:
```
  Warning  FailedCreatePodSandBox  3s    kubelet, kube-node02.example.com  Failed create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_test-0_default_bf1a93ca-7d08-11e9-897d-000c29616bad_0(11b89f695e8c2dbf7566be5ec743f9672460ecfdc26a2b6c4c8e0d819dd034d3): Multus: Err adding pod to network "macvlan-conf": Multus: error in invoke Conflist add - "macvlan-conf": error in getting result from AddNetworkList: invalid CIDR : invalid CIDR address:
```

If the `address` field is defined under `addresses` then the CIDR is defined but we get the below error since it is now define twice. Once in the CNI and again through the annotations:

```
  Warning  FailedCreatePodSandBox  0s    kubelet, kube-node02.example.com  Failed create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_test-0_default_ad270006-7d09-11e9-897d-000c29616bad_0(52554211ab2a2cf8d8cea5299bde22e93f0dddb936e242dd9eb48f1e0bb589e7): Multus: Err adding pod to network "macvlan-conf": Multus: error in invoke Conflist add - "macvlan-conf": error in getting result from AddNetworkList: failed to add IP addr {Version:4 Interface:0xc420014998 Address:{IP:10.0.30.30 Mask:ffffff00} Gateway:<nil>} to "net1": file exists
```

Thanks!

**Comment by s1061123** [comment]
@Elegant996 your issue seems not to related to the PR because multus does not support args for now. Could you show the diff if you have args supported multus code?

**Comment by Elegant996** [comment]
This looks to have been resolved by https://github.com/containernetworking/plugins/pull/343. Thanks!

**Comment by s1061123** [comment]
Need to update to fill missing args that is not in #343. Will be updated.

**Comment by dcbw** [comment]
@s1061123 can you update this PR and also fix the conflicts? Thanks!

**Comment by s1061123** [comment]
@dcbw hi, travis failed due to travis side error. Could you please rerun it? Rebase should be finished successfully.

**Comment by squeed** [comment]
lgtm!

**Pull request merged**
