### PR TITLE
Switch to ginkgo/v2

### PR DESCRIPTION
**Pull request by saschagrunert**
Update ginkgo to the next major version which has been released a while ago.

### CODE REVIEW

**Comment by squeed** [comment]
@saschagrunert thanks for this! Can you look in to the CI failure?

**Comment by saschagrunert** [comment]
> @saschagrunert thanks for this! Can you look in to the CI failure?

Ah yeah, fixing the structure :)

**Comment by squeed** [comment]
@saschagrunert bad news: ginkgo v2 breaks our tests, because it runs the BeforeEach and tests in separate goroutines. Sadly, our tests use BeforeEach extensively :(

**Comment by saschagrunert** [comment]
Hm, I have to look into this :thinking:

**Comment by saschagrunert** [comment]
@squeed may I ask you to re-approve?

**Comment by squeed** [comment]
@saschagrunert done. Fingers crossed :)

**Comment by squeed** [comment]
@saschagrunert not yet :(. But getting closer

**Comment by saschagrunert** [comment]
Another try please :)

**Pull request closed without merging**
