### PR TITLE
CI: Install linux-modules-extra for VRF module

### PR DESCRIPTION
**Pull request by squeed**

### CODE REVIEW

**Comment by squeed** [comment]
nope, it seems that none of the ubuntu versions for GH actions have vrf - @fedepaol, thoughts?

**Comment by fedepaol** [comment]
Actually, I spent a considerable amount of time in https://github.com/containernetworking/plugins/pull/526 to make it work.
IIRC, bionic (which is 18.04) supported it while xenial did not.

Let me dig a little more

**Review by mars1024 — APPROVED** [review]
/lgtm, well done!

**Review by thaJeztah — APPROVED** [review]
LGTM

**Pull request merged**
