### PR TITLE
Small typo improves in README.md

### PR DESCRIPTION
**Pull request by franciosi**
Small typo improves
Signed-off-by: André Franciosi <andre@franciosi.org>

### CODE REVIEW

**Comment by dcbw** [comment]
@franciosi could you add your DCO? `Signed-off-by: Your Name <your email>` thanks!

**Review by bboreham — APPROVED** [review]

**Comment by franciosi** [comment]
Did it @dcbw

**Review by mars1024 — APPROVED** [review]

**Comment by bboreham** [comment]
@franciosi to satisfy the checking mechanism it is necessary to change the git commit message and re-push your branch.

I can do this (push to your branch) myself if you like.

**Comment by franciosi** [comment]
Please do it @bboreham, or I can do it later today.
Thank you

**Comment by franciosi** [comment]
@bboreham, I did it in https://github.com/containernetworking/plugins/pull/628. I will close this PR.
Thank you

**Pull request closed without merging**
