### PR TITLE
added host-device plugin which adds a specified link to container

### PR DESCRIPTION
**Pull request by trusch**
Here is a plugin for moving host devices into container network-namespace.

The only parameter is "device".

Please review and tell me how to test this plugin, because I wasn't able to run the tests (or found documentation about how to do so...).

### CODE REVIEW

**Comment by dcbw** [comment]
I'd also suggest perhaps "hwAddress" as key which you could use for a MAC address match.  And perhaps "kernel path" so you can specify the interface through explicit PCI addressing, which is more stable than interface name or MAC address.  Here's some code for all that:

```
func findPhysdev(devname, hwaddr, kernelpath string) (netlink.Link, error) {
	links, err := netlink.LinkList()
	if err != nil {
		return nil, fmt.Errorf("failed to list node links: %v", err)
	}

	if len(devname) > 0 {
		if m, err := netlink.LinkByName(devname); err == nil {
			return m, nil
		}
	} else if len(hwaddr) > 0 {
		hwAddr, err := net.ParseMAC(hwaddr)
		if err != nil {
			return nil, fmt.Errorf("failed to parse MAC address %q: %v", hwaddr, err)
		}

		for _, link := range links {
			if bytes.Equal(link.Attrs().HardwareAddr, hwAddr) {
				return link, nil
			}
		}
	} else if len(kernelpath) > 0 {
		if !filepath.IsAbs(kernelpath) || !strings.HasPrefix(kernelpath, "/sys/devices/") {
			return nil, fmt.Errorf("kernel device path %q must be absolute and begin with /sys/devices/", kernelpath)
		}
		netDir := filepath.Join(kernelpath, "net")
		files, err := ioutil.ReadDir(netDir)
		if err != nil {
			return nil, fmt.Errorf("failed to find network devices at %q", netDir)
		}

		// Grab the first device from eg /sys/devices/pci0000:00/0000:00:19.0/net
		for _, file := range files {
			// Make sure it's really an interface
			for _, l := range links {
				if file.Name() == l.Attrs().Name {
					return l, nil
				}
			}
		}
	}

	return nil, fmt.Errorf("failed to find physical interface")
}
```

**Comment by dcbw** [comment]
For the testcases, here's what you do...

Put this into the BeforeEach():

```
	originalNS, err := ns.NewNS()
	Expect(err).NotTo(HaveOccurred())
```

and this into the AfterEach():

```
	originalNS.Close()
```

And then in the testcase itself:

```
err := originalNS.Do(func(ns.NetNS) error {
	defer GinkgoRecover()

	err := netlink.LinkAdd(&netlink.Dummy{
		LinkAttrs: netlink.LinkAttrs{
			Name: "dummy0",
		},
	})
	Expect(err).NotTo(HaveOccurred())

	link, err := netlink.LinkByName(ifname)
	Expect(err).NotTo(HaveOccurred())

	err = netlink.LinkSetUp(link)
	Expect(err).NotTo(HaveOccurred())

	return nil
})
Expect(err).NotTo(HaveOccurred())

<do the testcase>
```

**Comment by trusch** [comment]
@dcbw I added your function and extended the config struct accordingly. Other options to specify the device are indeed useful :)

**Comment by dcbw** [comment]
@trusch looks much better now, thanks!  But I don't see the corresponding testcase updates to add a dummy eth0 link.  I think as-is, the testcase is going to fail unless your machine has an eth0, which a lot of machines don't (because they use unique device names like enp0s25 or wlp4s0).  See https://github.com/containernetworking/plugins/pull/3#issuecomment-298441790 for how that could be done.

**Comment by dcbw** [comment]
@trusch ping on some testcase updates?  Thanks!

**Comment by dcbw** [comment]
@trusch any chance you can update the testcases and then we could get this merged?  thanks!

**Comment by trusch** [comment]
@dcbw I was really busy the last weeks, I will try to fix the testcase today. Good to hear that you guys are going to merge this :)

**Comment by trusch** [comment]
@dcbw: I fixed and extended the tests. I can not run the tests locally, because I don't find docs about how to setup a working dev env for CNI Plugins. However, CI is green so I hope they ran successfully.

**Comment by trusch** [comment]
@dcbw: I found a way to setup my dev env (docs are in containernetworking/cni). My kernel headers to get virtualbox running are still compiling ;)

**Comment by trusch** [comment]
@dcbw PTAL. I hope everything is good now.

**Comment by trusch** [comment]
Polite ping on this...

_Sent from my Htc HTC One_M8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by trusch** [comment]
@dcbw Will this ever be merged? If not I'll put this in a seperate repository so that it can be used by other people without to compile a fork of the cni-plugins repo. Its ok if you and the team don't see the general interest in this plugin, but please let me know.

**Comment by trusch** [comment]
@cni-maintainers Ping?

**Comment by dcbw** [comment]
LGTM

**Comment by squeed** [comment]
yeah, this is pretty cool. LGTM.

**Pull request merged**
