### PR TITLE
host-local support idempotent allocation

### PR DESCRIPTION
**Pull request by mars1024**
try to fix [https://github.com/containernetworking/plugins/issues/327](https://github.com/containernetworking/plugins/issues/327)

### CODE REVIEW

**Comment by dcbw** [comment]
Discussed this and we agree that this fixes a bug in host-local and is better than the current behavior. Could you update the plugin to instead return an error when an allocation exists for a given ID, since the spec mandates that plugins "must" not call ADD for the same tuple?

**Comment by mars1024** [comment]
> @mars1024 Discussed this and we agree that this fixes a bug in host-local and is better than the current behavior. Could you update the plugin to instead return an error when an allocation exists for a given ID, since the spec mandates that plugins "must" not call ADD for the same tuple?

OK, I'll update this soon. :)

**Comment by mars1024** [comment]
Updated!  cc @dcbw  
Now host-local will support idempotent allocation in this way, if a given ID has an allocated IP, the follow-up requests will be rejected until it release the allocated IP.

**Comment by mars1024** [comment]
@dcbw @squeed @bboreham @rosenhouse If you have time, please take a look at this updated PR this week, thanks a lot ~

**Comment by squeed** [comment]
lgtm, thanks!

**Comment by mars1024** [comment]
@dcbw @bboreham Could you help to promote the updated PR this week?

**Comment by dcbw** [comment]
LGTM

**Comment by squeed** [comment]
Done! We expect to be tagging another release next week.

**Pull request merged**
