### PR TITLE
Add IPv6 support for AddDefaultRoute

### PR DESCRIPTION
**Pull request by Y7n05h**
AddDefaultRoute assumes that the user is adding a default route for IPv4, not IPv6. This pr will fix it.

### CODE REVIEW

**Comment by mccv1r0** [comment]
Is there an issue with a description of something that isn't working?  AFAICT this function isn't used.

A few other things... 

1. adding default isn't either/or it maybe (and probably is) both unless single stack IPv6 is used.    If IPv4 is defined add `0.0.0.0/0`.  If IPv6 is used, add `::/0`.

2. The default route for IPv6 is (supposed to be) obtained via RA.

**Comment by Y7n05h** [comment]
> 2. The default route for IPv6 is (supposed to be) obtained via RA.

Usually the default route for IPv6 is automatically configured by Router Advertisements. But sometimes it is necessary to configure it manually.

- Some routing devices do not send Router Advertisements
- When there are multiple IPv6 devices, and the default route configured by Router Advertisements does not match the expected device

**Comment by mccv1r0** [comment]
> > 2. The default route for IPv6 is (supposed to be) obtained via RA.
> 
> Usually the default route for IPv6 is automatically configured by Router Advertisements. But sometimes it is necessary to configure it manually.



> * Some routing devices do not send Router Advertisements
> * When there are multiple IPv6 devices, and the default route configured by Router Advertisements does not match the expected device

**Comment by mccv1r0** [comment]
Closed due to lack of coffee.  Apologies 

> > > 2. The default route for IPv6 is (supposed to be) obtained via RA.
> > 
> > 
> > Usually the default route for IPv6 is automatically configured by Router Advertisements. But sometimes it is necessary to configure it manually.
> 
> > * Some routing devices do not send Router Advertisements

The (current) cloud world we live in sadly.   The PR makes sense as a result.  Is this for your plugin?  IIRC this isn't used by any of the CNI  reference plugins.  

> > * When there are multiple IPv6 devices, and the default route configured by Router Advertisements does not match the expected device

This I'm having a harder time parsing... "expected" device?  If the network tells you what to use it's best to use that and not what you expected.  I get 8 default routes from my ISP (cheapest plan), some come and go as ISP needs require.  It's safe for me not to expect any.

**Review by squeed — APPROVED** [review]

**Comment by squeed** [comment]
Note: This function isn't used by the plugins, I can't guarantee it continues to exist.

**Pull request merged**
