### PR TITLE
Update various dependencies in go.mod 

### PR DESCRIPTION
**Pull request by thaJeztah**
See individual commit messages for details

### CODE REVIEW

**Comment by thaJeztah** [comment]
Interesting; never seen such failures; https://github.com/containernetworking/plugins/pull/603/checks?check_run_id=2096902751

```
with coverage profile generation...
github.com/containernetworking/plugins/integration
# internal/unsafeheader
compile: version "go1.15.10" does not match go tool version "go1.15.8"
# internal/cpu
compile: version "go1.15.10" does not match go tool version "go1.15.8"
# runtime/internal/atomic
compile: version "go1.15.10" does not match go tool version "go1.15.8"
# runtime/internal/sys
compile: version "go1.15.10" does not match go tool version "go1.15.8"
# internal/race
compile: version "go1.15.10" does not match go tool version "go1.15.8"
# sync/atomic
compile: version "go1.15.10" does not match go tool version "go1.15.8"
# math/bits
```

**Comment by thaJeztah** [comment]
(temporarily) cherry-picked https://github.com/containernetworking/plugins/pull/604 in this branch to see if it solves the issue

**Comment by thaJeztah** [comment]
Problem resolved itself looks like; failures look to be because of https://github.com/containernetworking/plugins/pull/600

**Comment by thaJeztah** [comment]
I reverted the cherry-pick; looks like that brings back the failures;

```
# github.com/onsi/gomega/types
compile: version "go1.15.10" does not match go tool version "go1.15.8"
```

So looks like https://github.com/containernetworking/plugins/pull/604 is needed indeed

**Comment by thaJeztah** [comment]
rebase, as https://github.com/containernetworking/plugins/pull/604 was merged

**Comment by thaJeztah** [comment]
Seeing various failures, but not sure if introduced in this PR, or related to what's supported by machines in CI:

```
/home/runner/work/plugins/plugins/plugins/meta/vrf/vrf_test.go:77
  configures and deconfigures VRF with CNI 0.4.0 ADD/DEL [It]
  /home/runner/work/plugins/plugins/plugins/meta/vrf/vrf_test.go:534

  Unexpected error:
      <*errors.errorString | 0xc0004c1390>: {
          s: "cmdAdd failed: could not add VRF vrf0: operation not supported",
      }
      cmdAdd failed: could not add VRF vrf0: operation not supported
  occurred

  /home/runner/work/plugins/plugins/plugins/meta/vrf/vrf_test.go:568
```

**Comment by thaJeztah** [comment]
Guessing the above failure relates to https://github.com/containernetworking/plugins/pull/600

**Comment by thaJeztah** [comment]
🎉 this is green, now that #600 is merge

@squeed @mars1024 ptal

**Comment by dcbw** [comment]
LGTM

**Review by bboreham — APPROVED** [review]
Thanks!  I have not examined every line of this change.

**Comment by thaJeztah** [comment]
> Thanks! I have not examined every line of this change.

Pfff that's lame 😂 😉 😜 

Screenshot 2021-04-14 at 18 50 31

**Pull request merged**
