### PR TITLE
Change veth allocation to after IPAM.

### PR DESCRIPTION
**Pull request by thanset**
Related to Issue #29, this was replicated and tested with a small script.

```
#!/bin/bash

ip netns del test0
ip netns del test1

export DEBUG=1
export NETCONFPATH=/etc/cni/net.d/
export CNI_PATH=/home/tim/go/src/plugins/bin

ip netns add test0
ip netns add test1

./cnitool add test /var/run/netns/test0

echo "BEFORE"
ip addr show | grep veth
echo ""

./cnitool add test /var/run/netns/test1

echo "AFTER"
ip addr show | grep veth

./cnitool del test /var/run/netns/test0

echo "AFTER DELETION"
ip addr show | grep veth


unset DEBUG
unset NETCONFPATH
unset CNI_PATH
```

Right now the behavior is such that a veth will be allocated even after IPAM exhaustion but it will never be cleaned up on it's own, simply altering the order of operations (Veth allocation after IPAM is called) prevents this veth orphan from ever being created.

### CODE REVIEW

**Comment by thanset** [comment]
Looks like the tests for arch `Linux x86_64` have failed for port mapping, getting an Ip-tables error https://travis-ci.org/containernetworking/plugins/jobs/248013051#L669, looks like it's not finding the chain created by the test?  I'm not sure if this test is flakey?  Anyone have any input regarding this?

**Comment by squeed** [comment]
Hmm, sorry about that. (I wrote the portmap tests). I've kicked the job. Something is flaky about them.

**Comment by thanset** [comment]
@squeed Thanks for the review, I was unaware that was part of the spec-  I will add in tear down logic for this in case of IPAM exhaustion.  cc'ing @vzcambria so he's aware.

**Comment by squeed** [comment]
It is, indeed, barely mentioned in the spec. I'll try and make it clearer.

**Comment by thanset** [comment]
@squeed Updated my branch, I'm simply deleting the `args.IfName` in the namespace as is done in `cmdDel()` via `ns.WithNetNSPath()`.  However, the code is duplicated, would you suggest moving this into a separate function (style wise question- I'm unsure if a small bit of duplication is frowned upon here)?

**Comment by thanset** [comment]
@squeed The approach I took here was to call `cmdDel` if there was an error according to the spec. The particular section I was looking at was:  

```
An ADD action fails, when the runtime decides to handle the failure it should execute the DEL action (in reverse order from the ADD as specified above) for all plugins in the list, even if some were not called during the ADD action.
```

I wrapped this up in the function `cleanUpOnFailure()`.

**Comment by thanset** [comment]
@dcbw  Thank you kindly for the review and more elegant solution.  I've taken your approach and updated the branch.

**Comment by thanset** [comment]
@squeed Can you kick the travis test again to fix the build? Thanks! Seems to be the flakey test.

**Comment by rosenhouse** [comment]
Kicked

**Comment by squeed** [comment]
The test failed because I fixed a flake; can you squash and and rebase your commits on master? Thanks!

**Comment by thanset** [comment]
@squeed Done, squashed commits and rebased on master- but another version of Go on travis is breaking on the same test (Go v1.8 vs v1.7 before), still on amd64.

**Comment by thanset** [comment]
@squeed @dcbw Is there anything else holding this PR back from merge?

Thanks!

**Comment by squeed** [comment]
Changes look good to me - @dcbw, anything to add?

**Comment by thanset** [comment]
@rosenhouse @dcbw @squeed anything else to change before a merge? Thanks!

**Comment by thanset** [comment]
@squeed checking in a last time to see if there's anything else you'd like me to clean up before a merge, thanks.

**Comment by mauriciovasquezbernal** [comment]
@squeed could I know what is the reason it wans't merged?

**Pull request closed without merging**
