### PR TITLE
gha: update actions/setup-go@v2

### PR DESCRIPTION
**Pull request by thaJeztah**
The V2 offers: https://github.com/actions/setup-go#v2

- Adds GOBIN to the PATH
- Proxy Support
- stable input
- Bug Fixes (including issues around version matching and semver)

### CODE REVIEW

**Comment by thaJeztah** [comment]
failures look to be because of #600

**Comment by thaJeztah** [comment]
This looks to resolve the failure as seen in https://github.com/containernetworking/plugins/pull/603#issuecomment-797631113

> Interesting; never seen such failures; https://github.com/containernetworking/plugins/pull/603/checks?check_run_id=2096902751
> 
> ```
> with coverage profile generation...
> github.com/containernetworking/plugins/integration
> # internal/unsafeheader
> compile: version "go1.15.10" does not match go tool version "go1.15.8"
> # internal/cpu
> compile: version "go1.15.10" does not match go tool version "go1.15.8"
> # runtime/internal/atomic
> compile: version "go1.15.10" does not match go tool version "go1.15.8"
> # runtime/internal/sys
> compile: version "go1.15.10" does not match go tool version "go1.15.8"
> # internal/race
> compile: version "go1.15.10" does not match go tool version "go1.15.8"
> # sync/atomic
> compile: version "go1.15.10" does not match go tool version "go1.15.8"
> # math/bits
> ```
> 
> some information here; [golang/go#22814 (comment)](https://github.com/golang/go/issues/22814#issuecomment-345587860)

**Comment by thaJeztah** [comment]
@dcbw @squeed ptal

**Comment by squeed** [comment]
Thanks!

**Pull request merged**
