### PR TITLE
Add a bundled busybox-style build flavor.

### PR DESCRIPTION
**Pull request by jpeach**
Building all the Linux plugins as separate binaries results in a total
size of around 70MB. If we bundle them all into a single busybox-style
executable, this shrinks to around 7MB.

Signed-off-by: James Peach <jpeach@vmware.com>

### CODE REVIEW

**Comment by mars1024** [comment]
I appreciate your contribution, but usually only several (not all) plugins will be picked for using, so maybe the disk space is not a practical problem.

**Comment by jpeach** [comment]
> I appreciate your contribution, but usually only several (not all) plugins will be picked for using, so maybe the disk space is not a practical problem.

That's possible, though if you ever install more than 1 of these plugins, you will still save space.

However, there are also system that just install all the plugins because they don't know which ones will end up being used. for example Kubernetes image builder does [this](https://github.com/kubernetes-sigs/image-builder/blob/master/images/capi/ansible/roles/kubernetes/tasks/url.yml#L28).

**Comment by jpeach** [comment]
```
[jpeach@sk1 cni-plugins]$ rm -rf bin/
[jpeach@sk1 cni-plugins]$ ./build_linux.sh
Building plugins
building dhcp
building host-local
building static
building bridge
building host-device
building ipvlan
building loopback
building macvlan
building ptp
building vlan
building bandwidth
building firewall
building flannel
building portmap
building sbr
building tuning
building vrf
[jpeach@sk1 cni-plugins]$ du -sh bin
72M	bin <<<
[jpeach@sk1 cni-plugins]$ rm -rf bin/
[jpeach@sk1 cni-plugins]$ BUNDLE=Y ./build_linux.sh
Building plugins
building cni-plugins bundle
2021/03/22 07:38:19 Disabling CGO for u-root...
2021/03/22 07:38:19 Build environment: GOARCH=amd64 GOOS=linux GOPATH=/home/jpeach/go CGO_ENABLED=0 GO111MODULE= GOROOT=/usr/lib/golang PATH=/usr/lib/golang/bin:$PATH
linking dhcp
linking host-local
linking static
linking bridge
linking host-device
linking ipvlan
linking loopback
linking macvlan
linking ptp
linking vlan
linking bandwidth
linking firewall
linking flannel
linking portmap
linking sbr
linking tuning
linking vrf
[jpeach@sk1 cni-plugins]$ du -sh bin
7.6M	bin <<<
```

**Comment by bboreham** [comment]
It's a nice idea, but adds more ways for things to go wrong.
Given nobody ever opened an issue to complain about CNI plugin disk space, I say no thanks.

**Comment by jpeach** [comment]
> Given nobody ever opened an issue to complain about CNI plugin disk space, I say no thanks.

I guess I could have opened an issue to complain as well, but I thought I'd just fix it :)

**Pull request closed without merging**
