### PR TITLE
ipvlan support default route

### PR DESCRIPTION
**Pull request by chenk008**
When I use flannel with ipVlan, I need the default route in container.
Add "isDefaultGateway" in ipVlan,  ipVlan can work  in Kubernetes with 'l3s' mode.

### CODE REVIEW

**Comment by dcbw** [comment]
Typically this would be solved by adding the default route to the 'routes' section of the CNI configuration. Does that work for you?

```
{
    "cniVersion": "0.3.1",
    "name": "example",
    "type": "ipvlan",
    "ipam": {
        "type": "host-local",
        "subnet": "10.88.0.0/16",
        "routes": [
            { "dst": "0.0.0.0/0" }
        ]
    }
}
```

**Comment by chenk008** [comment]
> Typically this would be solved by adding the default route to the 'routes' section of the CNI configuration. Does that work for you?
> 
> ```
> {
>     "cniVersion": "0.3.1",
>     "name": "example",
>     "type": "ipvlan",
>     "ipam": {
>         "type": "host-local",
>         "subnet": "10.88.0.0/16",
>         "routes": [
>             { "dst": "0.0.0.0/0" }
>         ]
>     }
> }
> ```

Thank you for reviewing.
I use ipvlan with flannel in kubernetes.The ipam config is generated by flannel,and flannel do not has a config for route.So i think default route is need.

**Comment by dcbw** [comment]
Aha. So what we should do here is to modify the flannel plugin to accept an IPAM block like other plugins, and allow the 'routes' option in that block (but not the IP addressing stuff which flannel handles independently).

**Comment by chenk008** [comment]
@dcbw I use "isDefaultGateway" inspired by this bridge plugin.When i use flannel with bright , i have set isDefaultGateway=true.
Maybe flannel also need support  ipam config , but now flannel is not support.The flannel will fail for "'delegate' dictionary must not have 'ipam' field, it'll be set by flannel"

**Pull request closed without merging**
